### ISSUE TITLE
Update and test PKGBUILD

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-archlinux#1]
Most of the code here should be updated and ready to go. The `PKGBUILD` is a little messy since I don't really know the best practices for writing PKGBUILDs.

Please provide feedback here, and we can work from there.

**Comment by seppiofish** [comment]
I tesed and updated the PKGBUILD in #3.

I modified the PKGBUILD so that can be easily used with tags but still with commit hashes too, simply changing some variables.
Perhaps some other changes are in order if uniformity is a necessity because of #2. I personally would prefer the tag approach in accordance with main ungoogled-chromium own tags.
Just to explain bettere what I mean: in the package I maintain on AUR, I use a slightly modified version of the PKGBUILD in which I use the version variables (set to specific tags) in place of repo commit hashes so that the package (which I only update to tagged versions) remains consistent across upgrades and needs little maintaining. On the other hand it would be nice to leave the ability to use the PKGBUILD with any specific commit simply setting the desired hash. I struggle to find a clean solution that could satisfay both needs.

As of now the PKGBUILD is in an hybrid, working (with the pull request and the first tag), state, but not a very clean one.

**Comment by Eloston** [comment]
I don't know what use cases are more appropriate for Arch Linux here (I am not well-versed in Arch Linux's practices), so I went with a solution that tried to be more flexible/verbose at the cost of simplicity/elegance.

The only downside I can see with your implementation is that the PKGBUILD and associated configuration (namely GN flags and patches) will have a version that is tied to the main repo's tag version. More specifically, if you ever need to update the PKGBUILD or configuration independently (i.e. without changing the ungoogled-chromium files we are using), then I'm not really sure what we can do to version the changes that you've made and make a new release (without re-publishing the same version, which doesn't sound like an ideal situation).

An alternative I was considering was having a `pkgrel` be a number completely independent from ungoogled-chromium's revision number. However, that is also not ideal since it could be confusing with the format for ungoogled-chromium's tags.

So, I tried to adapt the versioning scheme I created for Debian/Ubuntu by pushing what is already in the repo. I used an underscore because I read that the Arch Linux PKGBUILD spec doesn't like non-integer `pkgrel` numbers, and I wasn't sure what option is best here.

Regarding the CI checks, we can adapt them to fit our needs later. How we specify the ungoogled-chromium version will determine how we fix the CI checks.

My overall goal is to set everything up in here so that it is easy for you and anyone else to make builds with the PKGBUILD directly. In other words, we should be able to just download the PKGBUILD and just build Arch Linux packages without any further modifications (from my understanding, this would be an idea situation for Arch Linux users). If you have a good solution for this, feel free to implement it.

**Comment by danbob** [comment]
I don't know much about AUR and PKGBUILDs either, but what about something like this version scheme: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-ozone-wayland-git
It looks like `<version number>+<revision>+<short commit hash>`. The hash could be added / left off as needed, and this method leaves `pkgrel` independent as it probably should be.

**Comment by nikolowry** [comment]
As an Arch user, I'd love for the new PKGBUILD's to focus on being able to build from the tip of ungoogled-chromium's tree. Most of us don't mind being guinea-pigs for new releases, so whatever you can do to get PKGBUILD's out quickly -- it will be much appreciated!

**Comment by nikolowry** [comment]
Wanted to share how I approached building from the lastest commits of each repo -- `ungoogled-chromium-git` essentially: https://github.com/nikolowry/ungoogled-chromium-archlinux/commit/1eaf182b5636b3d4a3b5031fc29c13751e4b1d3c

Introduced two new variables `_ungoogled_archlinux_version` and `_ungoogled_archlinux_repo` that emulate their `_ungoogled_{version,repo}` counterparts.

Some unrelated issues:

- The ungoogled-chromium repos in the `source` array needs to be in double quotes, expressions can't expand inside single-quotes: https://github.com/nikolowry/ungoogled-chromium-archlinux/commit/3d2d0d226e55697391509a10e5cb90b9a1831d57
- Consider adding a `.gitignore` for `pkg`, `src` and all tarballs: https://github.com/nikolowry/ungoogled-chromium-archlinux/commit/a8d284e6162fb9f623668646a91da2c70f8c563c
- `$srcdir` isn't defined until the script's `prepare` function -- `_ungoogled_repo` and `_utils` need to be declared inside of it. They'll still be defined in `build`

Let me know if you'd like me to open up a PR for any of these. Regardless of that, thanks for the continued maintaince of ungoogled-chromium!

**Comment by Eloston** [comment]
@nikolowry You can submit a PR for all of this. A few notes though:

* In the repo, I'd prefer if we use tags or commits instead of branch names for the new variables. Otherwise, the build will not be deterministic (because it will depend on whatever the HEAD of those branches are).
* Is the versioning scheme I introduced okay? Or should we switch it to something else? e.g. `73.0.3683.103-1.1` like it is on all the other configurations, even though it isn't recommended by Arch Linux.

**Comment by nikolowry** [comment]
@Eloston will do the next time I have a chance!

The use of `master` was more for a POC of building the latest -- they should still accept a commit hash or release tag (need to double-check Github's tar url scheme, but I'm 99% sure).  Will verify those scenarios before opening a PR

**Comment by nikolowry** [comment]
@Eloston I'm still planning on doing thorough research this week on https://wiki.archlinux.org to help with finalizing the transition to this new repo. Will report findings by 2019.04.26

**Comment by ang124875** [comment]
build fine today (27-04-2019) with _ungoogled_version=9fa9c7ad3d1191f1977efad7880e1f0fae9e792c

yielding ungoogled-chromium-74.0.3729.108-1-x86_64

if prepare() is modded like this:

  msg2 'Preparing patches.'
  cd "$_ungoogled_archlinux_repo"
  sed -i '/inox-patchset\/chromium-color_utils-use-std-sqrt.patch/d' ./patches/series
  sed -i '/inox-patchset\/chromium-media-fix-build-with-libstdc++.patch/d' ./patches/series
  sed -i '/debian_buster\/fixes\/vaapi.patch/d' ./patches/series
  sed -i '/debian_buster\/disable\/installer.patch/d' ./patches/series
  sed -i '/debian_buster\/warnings\/explicit-constructor.patch/d' ./patches/series
  sed -i '/debian_buster\/system\/event.patch/d' ./patches/series
  sed -i '/debian_buster\/system\/openjpeg.patch/d' ./patches/series

**Comment by ang124875** [comment]
built successfully without modifications with latest commit 6e1b7c322c3ff3e7e4c14ebf87b7bfa60241e6c6

**Comment by ang124875** [comment]
Finished making: ungoogled-chromium 74.0.3729.131-1 with _ungoogled_version=8376a54fc82d959c38b31a69fbfa1d08e5aaf711

**Comment by ostkind** [comment]
Tried 74.0.3729.108 today but failed while "Pruning binaries":
python: can't open file '/var/tmp/makepkg/ungoogled-chromium-archlinux/src/ungoogled-chromium-archlinux-9fa9c7ad3d1191f1977efad7880e1f0fae9e792c/utils/prune_binaries.py': [Errno 2] No such file or directory

**Comment by nikolowry** [comment]
Apologizes for my lateness (again) @Eloston ! My time was limited the past week.

After reading through the wiki, I believe there's just two viable paths forward in getting this repo up to AUR

**1) Update https://aur.archlinux.org/ungoogled-chromium.git to be a mirror of this remote**

Whomever has write access to AUR's repo will need to do some creative "git-fu" to get this repo and the AUR one in sync and having a shared history.

The best how-to I could find was the accepted answer from this StackOverflow question https://stackoverflow.com/questions/2428137/how-to-rebase-one-git-repository-onto-another-one

**2) Create a new AUR package, `ungoogle-chromium-archlinux`, that replaces the out-of-date one**

If getting the remotes history synced turns out to be too difficult, you could always just start fresh and create a new AUR package named `ungoogled-chromium-archlinux`.

The PKGBUILD would need to add `replaces=ungoogled-chromium` and possibly `provides=ungoogled-chromium`.

---

Regardless of which option you decide to take, it is also might be a good idea to check in a `.SRCINFO` to prevent any divergence from happening once they are in sync

**Comment by Eloston** [comment]
@nikolowry 

> Apologizes for my lateness (again) @Eloston ! My time was limited the past week.

No worries.

> After reading through the wiki, I believe there's just two viable paths forward in getting this repo up to AUR

How about the versioning issue? Is it fine to leave it the way it currently is? To clarify, this would imply that any changes to the PKGBUILD or patches in this repo would not show up as a new version in the AUR unless we also update the ungoogled-chromium submodule to a new version.

> 1) Update https://aur.archlinux.org/ungoogled-chromium.git to be a mirror of this remote
> Whomever has write access to AUR's repo will need to do some creative "git-fu" to get this repo and the AUR one in sync and having a shared history.

If we don't care about the history in the AUR, we can just `git push --force` from this repo to the AUR's repo. The old history will be sent to oblivion (almost) and this repo's history will take its place. However, I don't know if this will cause any issues with systems reading that git repo or not.

Rebasing will be more difficult because:

* Rebasing the AUR's repo onto ours would mean the AUR repo's history would no longer be the same, and that's no better than `git push --force`
* Rebasing our repo onto the AUR's repo would make synchronization difficult for the AUR repo, unless we force push the rebased branch into this repo. This would take some effort to do correctly, such as commit signatures.

> 2) Create a new AUR package, ungoogled-chromium-archlinux, that replaces the out-of-date one

This is the simpler option, but I don't like it as much because the name isn't very nice. We can use this as a fallback.

**Comment by nikolowry** [comment]
@Eloston seems like you got the git stuff handled!

> How about the versioning issue? Is it fine to leave it the way it currently is? To clarify, this would imply that any changes to the PKGBUILD or patches in this repo would not show up as a new version in the AUR unless we also update the ungoogled-chromium submodule to a new version.

I think the versioning is fine, mainly because this repo will always be downstream and dependent to `ungoogled-chromium`. The patches and `PKGBUILD` are always going to be implicitly tied to whatever `_ungoogled_version` is set to. 

Keeping that in mind, post-release commits that are unique to this repo should only really occur when a "hotfix" is needed -- whether that be in the `PKGBUILD` or the ArchLinux specific patches. Are there any other valid "user-stories" you can think of when the `pkgrel` in the `PKGBUILD` could diverge from the release in the ungoogled-chromium repo?

What about doing something like this for the `pkgrel`:
```
_ungoogled_archlinux_pkgrel=0
pkgrel=$((_ungoogled_revision + _ungoogled_archlinux_pkgrel))
```

For every new version, `_ungoogled_archlinux_pkgrel` would be reset to 0 and should only temporarily increase in edge-case scenarios.

**Comment by Eloston** [comment]
@nikolowry Just to ensure we agree on the implications, your scheme will work if you reset `_ungoogled_archlinux_pkgrel` only when `_chromium_version` is updated. It will not always work when `_ungoogled_version` is updated, because only `_ungoogled_revision` may change, and you will end up conflating versions together (i.e. the sum would be the same even though the operands changed)

Off the top of my head, the only downside I can think of is the user will not be able to determine what underlying ungoogled-chromium version they are using by looking at the `pkgrel` alone. This could become a little inconvenient if a user wants to determine if some new features or fixes from the ungoogled-chromium repo has landed in this repo or not. However, if you believe this is not an issue, then your scheme should be fine.

**Comment by nikolowry** [comment]
@Eloston if by user you mean an AUR end-user, they shouldn't need to check the `PKGBUILD` for that information. It will instead be in `.SRCINFO`, and that meta will be used to populate the details in https://aur.archlinux.org/packages/ungoogled-chromium and in AUR helpers (e.g yay, pacaur, pakku, pikaur).

However, it might not be a bad idea to document all of this for future contributors -- especially since the `PKGBUILD` is very unique to most the other ones currently in AUR.

---

Let's go over some example scenarios of how I imagine the scheme to work, hopefully they will clarify the intended usage:

**1) AUR users are reporting unsuccessful builds on a new release**
 A new version of `ungoogled-chromium` -- `74.0.3729.131-1` -- is released.  Following that release, `ungoogled-chromium-archlinux`'s `PKGBUILD` is updated with the new commit hashes, a newly generated `.SRCINFO` is checked-in and is finally followed by a premature push to AUR's git remote (before the maintainer was able to successfully validate a local build).

Issues are now being opened due to build errors deployed, and a new release needs to be pushed to AUR.  This is only relevant to `ungoogled-chromium-archlinux`, so the `_ungoogled_archlinux_pkgrel` is incremented from 0 to 1.  The fixes are pushed to AUR's git remote with a newly generated `.SRCINFO` with the final version becoming `74.0.3729.131-2`. 

The next commit targeting a new `ungoogled-chromium` release (i.e. not `74.0.3729.131`) needs to reset the `_ungoogled_archlinux_pkgrel`, otherwise the next version released to AUR will have `-2` appended.

**2) `ungoogled-chromium` increments the release on the current version**
A new version of `ungoogled-chromium` -- `73.0.3683.103-1` -- is released. A revision needs to be released to all platforms - `73.0.3683.103-2`.  If `_ungoogled_archlinux_pkgrel` is as 0, `-2` will be appended when generating `.SRCINFO`.

The only time `ungoogled-chromium`'s and `ungoogled-chromium-archlinux`'s release numbers should diverge if there is a change required in AUR that isn't required in `ungoogled-chromium`

---

This was the only obvious way to allow for flexibility of the two repo's release revisions.  The only downside is maintainers of this repo will need to stay conscience to the fact that the number needs to be maintained and reset.  The only suggestion I can think of to make maintaining it easier would be to add some bash utils (maybe some type of prompt GUI?) that could be easily plugged into git hooks.

**Comment by Eloston** [comment]
@nikolowry Alright, you've convinced me. Good write-up. As usual, I'll accept PRs for documentation changes and/or scripts to manage the revision numbers more easily for anyone interested.

**Comment by nikolowry** [comment]
@Eloston seems like someone went ahead and created a new AUR package, https://aur.archlinux.org/packages/ungoogled-chromium-archlinux.

The bright side is users have been attempting to build via AUR helpers and are reporting issues in the comment. `makepkg` and some AUR helpers aren't one to one, so be on the look out for PR requests if any changes are needed.

**Comment by nikolowry** [comment]
@Eloston the unofficial AUR package was updated today to incorporate #12 and I'm happy to report `yay` was able to start a build successfully (I aborted to prevent `ungoogled-chromium-archlinux` from replacing my local `ungoogled-chromium` builds).

I think it's safe to say that this is ready for AUR, so feel free to get this pushed up at your convenience. 

If you don't have any availability to sync the remotes and also feel comfortable giving me write access to the AUR remote -- I'd be glad to tackle it during a weekend. Feel free to ping me here if that's the case and we can work it out.

And last but not least I can't say thank you enough for how long this has been actively maintained -- every other project that's attempted "ungoogling" is quickly abandonded due to maintainers underestimating the work needed in updating patches between revisions.

**Comment by Eloston** [comment]
@nikolowry 

> If you don't have any availability to sync the remotes and also feel comfortable giving me write access to the AUR remote -- I'd be glad to tackle it during a weekend. Feel free to ping me here if that's the case and we can work it out.

I don't have access to that. You should work with @seppiofish, he's the current maintainer.

> And last but not least I can't say thank you enough for how long this has been actively maintained -- every other project that's attempted "ungoogling" is quickly abandonded due to maintainers underestimating the work needed in updating patches between revisions.

Right back at you. You guys provide platform support and updates to the latest versions of Chromium; two very important factors for the users that I can't maintain on my own.

**Comment by nikolowry** [comment]
@seppiofish any eta on push to AUR? Same offer is extended to you if you need any help

**Comment by seppiofish** [comment]
@Eloston @nikolowry I'm sorry but I've been very busy and could not reply to you.

I just updated the PKGBUILD on AUR and I read about your versioning schemes proposals.
I must admit that I'm a bit confused about this repo versioning differentiation purposes and I will give it a second look as soon as I can, which this time I hope won't be to long. For now I can say that summing up the revision numbers from ungoogled-chromium and this repo is a solution that I personally don't like a lot, since information about specific releases from the two repo are lost in the final version of the package and unless someone can read the PKGBUILD, they could not know whether a 4 is a 3+1 or a 1+3 for example. Anyway, whether this would be adopted as versioning scheme or not, I think appropriate tags should be used.

In the meantime I will promptly update AUR PKGBUILD as soon as a new version comes out, using the git commit hash as versioning for archlinux repo.

**Comment by Eloston** [comment]
@seppiofish 

> For now I can say that summing up the revision numbers from ungoogled-chromium and this repo is a solution that I personally don't like a lot, since information about specific releases from the two repo are lost in the final version of the package and unless someone can read the PKGBUILD, they could not know whether a 4 is a 3+1 or a 1+3 for example. 

There is an additional constraint on the versioning; the PKGBUILD revision number will continue to increment until the next Chromium release. Thus in your example, if 1+3 exists, then 3+1 cannot exist for the same Chromium version. If the PKGBUILD revision doesn't change from 1+3, then you'd end up having 3+3 after two ungoogled-chromium revisions. So, this versioning scheme is bijective (i.e. forms a one-to-one mapping).

I also don't personally like how this scheme obscures the revision numbers, but it does allow us to conform to the recommended tag format for the AUR. Unless this scheme poses significant problems, then I don't think it's necessary to change it, unless someone here wants to.

**Comment by nikolowry** [comment]
Agree with @Eloston -- while the code is obfuscated and not self-documenting, it was the only "quick fix" to achieve the desired functionality.

Regardless of whether someone is able to provide a more elegant solution, we should strive to have the AUR be a downstream mirror of this repo. 

It will benefit everyone consuming this package if there's only a single source of truth of a `PKGBUILD` (currently there's 3). It should also make maintaining the AUR repo a little easier @seppiofish and help prevent extended durations of 'out-of-date' packages
