### ISSUE TITLE
GCC 11 related build issues

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-archlinux#130]
It seems like the latest version of GCC broke the build. Applying this patch https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/1453d87fe8ced77bd6e28b7b149f4af16bc7463a made it compile further but an error occurs at `obj/sql/sql/module.o` now (see [the ci log](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/runs/2604544932#step:8:15961))

**Comment by Ahrotahn** [comment]
I found an upstream bugreport about this [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1189788) and started working on a fix.  
Checking back on it again it seems @foutrelis found the fix was already submitted [here](https://chromium-review.googlesource.com/c/chromium/src/+/2862724)!  
I'll test building with this as I get time today.

**Comment by foutrelis** [comment]
I also came across this segfault at browser shutdown: https://crbug.com/1190561

**Comment by Ahrotahn** [comment]
Thanks for the heads-up!  
I had build stable again, so the issue causing the segfault hasn't been introduced yet.  I guess that's something that'll need to be addressed for next week though.  

My build with Stephan's changes finished successfully and seems to have no issues so far.  I'll submit a PR with the changes later today.

**Comment by foutrelis** [comment]
@Ahrotahn  Ah, you're right, it seems to only affect Chromium 91. I was trying out the latest beta in preparation for the stable release on Tuesday and incorrectly blamed the segfault on GCC 11.
