### ISSUE TITLE
ICU Rebuild

### ISSUE THREAD

**Issue by networkException** [ungoogled-software/ungoogled-chromium-archlinux#156]
icu-70.1-1 is currently in testing, I will publish a new release once it gets to core

**Comment by yuannan** [comment]
It's now live and have broken my setup.
`
/usr/lib/chromium/chromium: error while loading shared libraries: libicuuc.so.69: cannot open shared object file: No such file or directory
`
Can this package in the future be dynamically linked to "/usr/lib/libicui18n.so"? Or at least be packaged in a way to have version dependencies to be considered.

Thank.

**Comment by networkException** [comment]
> Can this package in the future be dynamically linked to "/usr/lib/libicui18n.so"? Or at least be packaged in a way to have version dependencies to be considered.

This is more or less just a seperately maintained "mirror" of extra/chromium with ungoogled-chromium patches (of course) and usually I'll try to stay as close to arch upstream. If its just a simple change I will consider it tho

**Comment by jstkdng** [comment]
@yuannan that sadly can't be done as C++ uses name mangling and when icu updates the library name will be the same but the functions inside will have different names, otherwise just symlinking the new library version to the previous name would fix the issue but sadly it doesn't.
```
$ chromium
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: _ZN6icu_698TimeZone13createDefaultEv
```
You can try out the following projects to avoid further library issues:
1. https://github.com/ungoogled-software/ungoogled-chromium-portablelinux
2. https://guix.gnu.org/en/packages/ungoogled-chromium-96.0.4664.45-1/
