### ISSUE TITLE
manjaro

### ISSUE THREAD

**Issue by lacostya86** [ungoogled-software/ungoogled-chromium-archlinux#170]
After latest update of ungoogled-chromium package on freshly installed and updated Manjaro I met the dependency hell.
Application wants to see glibc = 2.34 instead of installed 2.33 (pacman -Syu and specifying nor =2.34 or =2.35 didn't help).
I can't find the way to install proper version manually. Regarding [this issue](https://github.com/trinker/pacman/issues/81) - pacman still can't do this? 

$ uname -a
Linux laptop 5.15.19-2-rt29-MANJARO #1 SMP PREEMPT_RT Sat Feb 5 21:23:00 CET 2022 x86_64 GNU/Linux

$ chromium -v
chromium: /usr/lib/libc.so.6: version `**GLIBC_2.34**' not found (required by chromium)

$ sudo pacman -Q | grep -i glibc
glibc **2.33-5**
lib32-glibc **2.33-5**

sudo pacman -Q | grep -i ungoo
ungoogled-chromium **98.0.4758.102-2**

Should I manually install glibc => 2.34 and how to do this?
Should I downgrade ungoogled-chromium until this issue (is this issue) will be solved?

Thanks!

**Comment by networkException** [comment]
This is a duplicate of #169

You could change the Manjaro package branch to "unstable", that already contains an up to date version of glibc (see https://manjaro.org/branch-compare/). 
Here's a guide to switch branches https://wiki.manjaro.org/index.php?title=Switching_Branches

Downgrading any browser is bad idea as security bugs get discovered all the time

I hope the package gets promoted in a timely manner, otherwise it might actually be nessesarry to maintain a seperate branch for manjaro releases

Alternatively you could also use the flatpak release of ungoogled-chromium, that ships with all required dependencies by itself and runs in a sandbox

**Comment by lacostya86** [comment]
Thank you! Miswatched that closed issue, sry :) Okay, forgot at all about Flatpak, 10x, try!!
