### ISSUE TITLE
Cannot open ungoogled chromium after updating it (Manjaro Gnome Stable, latest version)

### ISSUE THREAD

**Issue by Miki200v2** [ungoogled-software/ungoogled-chromium-archlinux#180]
Ungoogled Chromium does not start after pacman updated it when i updated all packages, it does not even start as a process in the background, just completly does not start.
No other thing can be observed.

**Comment by networkException** [comment]
Whats the output of running `chromium` in the terminal?

**Comment by Miki200v2** [comment]
> Whats the output of running `chromium` in the terminal?


`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.71: cannot open shared object file: No such file or directory`

**Comment by networkException** [comment]
Alright, as the manjaro packages have not updated icu yet you will have to manually downgrade to https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/100.0.4896.127-1 for now.

To do that download the `ungoogled-chromium-100.0.4896.127-1-x86_64.pkg.tar.zst` file and run `pacman -U ungoogled-chromium-100.0.4896.127-1-x86_64.pkg.tar.zst` afterwards

**Comment by Miki200v2** [comment]
This fixed it, thanks.

**Comment by networkException** [comment]
I think I will keep this open for visibility until manjaro gets the updated version

**Comment by micro-elai** [comment]
is in the coming future will be a repo for manjaro just like the arch linux one, cuz that will solve a lot problems, a lot of people don't wanna use brave or other crappy browser with built in crypto currency and only wanna use ungoogle chromium, i added the OBS repository but it gets updated constantly so it's not an option for me, even if i had a powerful system that can build ungoogled chromium from the aur, stuff gonna break cuz manjaro delay their updates, i wanna use arch linux but i always get problems, manjaro test a lot of stuff before sending updates, if we had a repo for manjaro just like debian, android, macos,  or windows that will be very much appreciate it, thanks anyway though for the other repos and hard work so that people with less powerful hardware can experience a well made web browsing.

**Comment by networkException** [comment]
Yes I'm planning to add a seperate manjaro build eventually. Not in the near future however

**Comment by micro-elai** [comment]
thank you @networkException i will be on lookout for this.

**Comment by jstkdng** [comment]
you could theoretically use a manjaro docker image (https://hub.docker.com/r/manjarolinux/base) and use this repo's action to build a manjaro package, unless a patch is released that has to deal with a new package version that isn't in manjaro but it's on arch.
A separate ungoogled-chromium-manjaro repo should be created imo, to deal with those exceptions I mentioned.

**Comment by networkException** [comment]
I havent found manjaro specific chromium patches yet so I assume that they just use the archlinux ones? In that case running another action here is considerably less effort compared to maintaining a seperate repository

**Comment by jstkdng** [comment]
Not manjaro specific patches, arch patches that shouldn't be applied to manjaro because the library version is different on arch and manjaron and it might not apply. There have been icu patches that could not be applied to manjaro because old iirc.

Ofc you could just manually trigger the action once it's updated but that would be really cumbersome. Tbh a manjaro user should handle the manjaro stuff and not an arch user, that's just a lot of additional work that you won't be able to use.

**Comment by shuvashish76** [comment]
> Whats the output of running `chromium` in the terminal?

`/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/chromium/chromium)`

For that reason recently (about 1 month) I installed librewolf-bin [AUR](https://librewolf.net/installation/arch/) as secondary browser but same issue after it got updated today.

`/usr/lib/librewolf/librewolf: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/librewolf/librewolf)`

**Comment by networkException** [comment]
Yea, see #183

**Comment by shuvashish76** [comment]
> Now I don't have a browser on my system :(

Update: I moved to [Firefox](https://www.mozilla.org/en-US/firefox/all/#product-desktop-release) `.tar` version temporarily till manjaro devs fix it. There are appimages for all browsers but I don't like appimages & FF tar version gets updated automatically...

@networkException Do these [Portable Linux](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/) versions get updatedautomatically just like FF tar version?

**Comment by networkException** [comment]
No ungoogled-chromium build has updating on its own, they all need to rely on some package manager
