### ISSUE TITLE
Can't upgrade browser: Maximum file size exceeded

### ISSUE THREAD

**Issue by pozitp** [ungoogled-software/ungoogled-chromium-archlinux#202]
Other packages updating without any problems. Only ungoogled-chromium give me that error. How to fix that? 
![image](https://user-images.githubusercontent.com/61188367/190915333-1bc9c920-759f-4c57-a456-59351352b71b.png)
I don't have that problem before last repo update(-'s)

OS: Linux arch 5.19.8-zen1-1-zen
FS: Btrfs
Repo: OBS Production

**Comment by networkException** [comment]
I think this is due to a rebuild that didn't update the repository metadata properly. For now you should be able to upgrade by downloading `wget https://download.opensuse.org/repositories/home:/ungoogled_chromium/Arch/x86_64/ungoogled-chromium-105.0.5195.125-2-x86_64.pkg.tar.zst` and installing `pacman -U ungoogled-chromium-105.0.5195.125-2-x86_64.pkg.tar.zst` the package manually
