### ISSUE TITLE
Manjaro: ungoogled-chromium-bin is missing glibc 2.38.

### ISSUE THREAD

**Issue by geos-github** [ungoogled-software/ungoogled-chromium-archlinux#232]
Ungoogled-chromium-bin 115.0.5790.170-1 AUR on a Manjaro installation refuses to launch and complains it cannot find GLIBC_2.38.
Indeed glibc is still at 2.37. Is installing (compiling) the non-bin version the only way out for the time being?

**Comment by networkException** [comment]
Yes. There will not be binaries compatible  with whatever desync glibc version Manjaro is shipping.

**Comment by KataFF** [comment]
They are holding back 2.38 due to an apparent regression it has, see:
https://forum.manjaro.org/t/testing-update-2023-08-09-kernels-gamescope-plus-nvidia-kde-git-haskell-perl-python/145957/8
https://sourceware.org/bugzilla/show_bug.cgi?id=30723

**Comment by KataFF** [comment]
You can switch to `testing` branch of Manjaro - [see how](https://wiki.manjaro.org/index.php/Switching_Branches), where `ungoogled-chromium-bin` works just fine, though you might want to install a newer kernel than `6.1` (the current LTS) because the changes present on testing cause a kernel panic upon booting for some.

**Comment by UtoECat** [comment]
The manjaro stable branch has been updated, including glibc to version 2.38. This issue should be closed.
