### ISSUE TITLE
Crash right at the first time when I launch after install 

### ISSUE THREAD

**Issue by jasursadikov** [ungoogled-software/ungoogled-chromium-archlinux#252]
After installing a binary version of ungoogled-chromium it is not able to launch.
When you do launch from console. you see the following error message:
`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory`

![image](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/assets/14846427/a4526b27-6396-4ee5-8e6a-732cdc50fd75)

**Comment by jxir** [comment]
You need to wait until the rebuild against ICU 74 is finished.

**Comment by jasursadikov** [comment]
@jxir I got it from `paru`

**Comment by jxir** [comment]
So if you installed Ungooled Chromium via `paru`, which is an AUR helper script, then you have [this AUR package](https://aur.archlinux.org/packages/ungoogled-chromium-bin). As of now it installs [this binary](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/releases/tag/120.0.6099.109-1), which is built against ICU 73 and therefore broken on an up-to-date Arch system.

I expect the AUR package to be updated within the next 12 or so hours.

Alternatively you could try to downgrade your `icu` package. In the past I found this to be troublesome because of interdependencies with `harfbuzz`, `harfbuzz-icu` and other packages.

Another alternative would be to the OBS repository. [Setup instructions](https://software.opensuse.org//download.html?project=home%3Aungoogled_chromium&package=ungoogled-chromium)

**Comment by jxir** [comment]
@jasursadikov The AUR package has been updated!

**Comment by jasursadikov** [comment]
Thanks! Now I am free to switch to this browser.
