### ISSUE TITLE
Chromium freezes when an alert window pops-up

### ISSUE THREAD

**Issue by awsms** [ungoogled-software/ungoogled-chromium-archlinux#257]
I'm using i3wm. Whenever a JS alert pops-up, chromium freezes and I've to manually kill all chromium instances.
No idea where I should report this bug but that's the package I'm using.

100% reproducible for me with the following steps:
- create a bookmark for a wbesite (ctrl+D)
- under folder, click "Choose another folder..."
- freezes when the folders list pops up

```
chromium --version
Chromium 121.0.6167.139 Arch Linux
```

**Comment by i27i13** [comment]
Suffering from the same issue here!
Also happenes when I try to:
* Create a new Profile
* Open **more** than 14 Bookmarkes
* Rename any Bookmark Folder
* Edit any Bookmark
* Add new Extensions (Drag & Drop Any_File.crx)
* Add new Extensions (Load Unpacked)


Linux Arch (Manjaro)
Version 121.0.6167.160 (Official Build, ungoogled-chromium) (64-bit)

**Comment by networkException** [comment]
Does this happen with vanilla chromium as well?

**Comment by i27i13** [comment]
> Does this happen with vanilla chromium as well?

Just installed
Chromium Version 121.0.6167.85 (Official Build) Arch Linux (64-bit)
on Linux Arch (Manjaro), and still have the same issue!
Video demonstration:
streamable.com/9uojqy

I also had an empty/clean profile (deleted it because I thought it might be the cause), and tested on it before deleting.
The issue still persisted!

**Comment by networkException** [comment]
well I fear there's not much we can do if this is an upstream issue, you can try filing a bug report there

**Comment by SvenMeyer** [comment]
@awsms @i27i13 
- Does this only happen with i3wm ?
- Did that start just with 121 ?

**Comment by i27i13** [comment]
> @awsms @i27i13
> 
> * Does this only happen with i3wm ?
> * Did that start just with 121 ?

I am on XFCE, and it is still happening.

Chrome Version 123.0.6300.3 (Official Build) dev (64-bit) --- It is fixed ---
Chrome Version 121.0.6167.184 (Official Build) (64-bit) ------ It still presist, patially fixed! If you press "return/enter" enough times, then restart the browser! --- 
Ungoogle-Chromium Version 121.0.6167.184 (Official Build, ungoogled-chromium) (64-bit) --- It still presist ---

**Comment by PF4Public** [comment]
So it is upstream issue then?

**Comment by i27i13** [comment]
> So it is upstream issue then?
I do not know!

Good update!
I just changed the theme from **Classic** to **GTK**, and the problem partially disappeared!
I have to test some more because it might happen again! I now can:
* Open more than 14 Bookmarks
* Rename any Bookmark Folder
* Edit any Bookmark
* Add new Extensions (Drag & Drop Any_File.crx)
* Add new Extensions (Load Unpacked)

Still cannot:
* Create a new Profile

**Comment by awsms** [comment]
fixed upstream

**Comment by i27i13** [comment]
> fixed upstream

Reference?
