### ISSUE TITLE
Why no release for 124.0.6367.118-1?

### ISSUE THREAD

**Issue by playgithub** [ungoogled-software/ungoogled-chromium-archlinux#264]

**Comment by Stephen-Seo** [comment]
I think it's because the CI build failed (I also ran into the same build error).

If you look at the commit https://github.com/ungoogled-software/ungoogled-chromium-archlinux/commit/01bfffd9d7f2ed2019170b54dced7a7b580816a4 you can see that the CI job failed. If you inspect the CI job https://github.com/ungoogled-software/ungoogled-chromium-archlinux/actions/runs/8952501750/job/24597745739 , you can find that there was a build error.

**Comment by networkException** [comment]
Yea, there were issues with ninja 1.12 that pretty much caused the previous two releases to fail. Should be fixed in .115
