### ISSUE TITLE
openjpeg2 linking error

### ISSUE THREAD

**Issue by braewoods** [ungoogled-software/ungoogled-chromium-archlinux#73]
Analysis in #57 reveals it to be most likely related to the Clang lld linker in some capacity. It succeeds when the linker is switched to something else like GNU ld. We should try to find a solution beyond simply disabling it but for now there's not many options.

**Comment by Rowisi** [comment]
Maybe compiling openjpeg2 from source code and statically linking it would work?
I am not an expert but I think static linking would solve this problem.

**Comment by braewoods** [comment]
That's what already happens. It bundles a bunch of internal libraries. This was just an attempt to get it to use the system library.

**Comment by Rowisi** [comment]
I understand now, so removing system flags will increase compilation time.

**Comment by braewoods** [comment]
Hm. I'm chasing a lead with the linker. It might be possible to force it to link in spite of the seemingly missing symbols. All we care about is it executing correctly so this might be a viable solution.

**Comment by Eloston** [comment]
In reply to https://github.com/ungoogled-software/ungoogled-chromium-archlinux/issues/57#issuecomment-623028459, I believe those `use_system` values persisted from Inox and whoever touched the PKGBUILD. There's no reason why we need to keep them. In fact, it could be better to fork the upstream PKGBUILD directly instead of trying to maintain a custom PKGBUILD, but I'm not well-versed enough in the details to choose an option.

I did a quick search, and I'm wondering if this could be related? https://bugs.llvm.org/show_bug.cgi?id=45034

**Comment by braewoods** [comment]
@Eloston It could be. If so we should try this again later when Arch has updated their Clang to a newer version and/or rebuilt their openjpeg package.
