### ISSUE TITLE
Vaapi is still broken.

### ISSUE THREAD

**Issue by Ph0rk0z** [ungoogled-software/ungoogled-chromium-archlinux#81]
With the bug closed I tried UGC from the chaotic AUR. What do I see? ffmpeg video decoder.

It's not fixed from what I can tell :(

**Comment by wchen342** [comment]
Can you describe the problem you encoutered and also any log/console output?

**Comment by jstkdng** [comment]
Well, chaotic-aur is a third party repository, you should ask them to update, not us.

**Comment by wchen342** [comment]
Wait what? I though chaotic is an adjective?

**Comment by Ph0rk0z** [comment]
There are 2 different versions in there now. I moved to the (master branch) version and it works there. But in the whole numbered release version does not. btw, chaotic builds every x hours from source automatically.

**Comment by jstkdng** [comment]
it's a repository, and the AUR package also updated to the newest patches.

**Comment by jstkdng** [comment]
@Ph0rk0z 
that is to be expected. Maybe in the next chromium release the patches will be added. Or you could ask them to increment the release and include the patches.

**Comment by Ph0rk0z** [comment]
yes, I'll hold my nose and update on ubuntu to see what is happening there. but I think it must be in the git.  I have version 4044.138.1.rc0.gc8e02bd-4 but 129-2 and 138-1 didn't seem to work.

**Comment by wchen342** [comment]
Actually about the AUR, @Eloston the `README` currently point to seppia's version on AUR but I think we should add @jstkdng's `-git` repo too since he is now maintaining part of this repo and updates much more frequently.

**Comment by jstkdng** [comment]
@Eloston I think the vaapi patches should be included in the main repo as everyone can benefit from them. What do you think @wchen342 ?

**Comment by jstkdng** [comment]
@Ph0rk0z what do you mean?

**Comment by Ph0rk0z** [comment]
There are 2 aur packages that chaotic buids. One was git the other was release-y 

"add @jstkdng's -git repo too"

That sounded like you have a package in the AUR too.

**Comment by wchen342** [comment]
> I think the vaapi patches should be included in the main repo

There is one more patch other than `vaapi-build-fix.patch` and `vdpau-support.patch`?

> Still will have to wait for you to accept my prs

You mean #76 or in the future? I should be online quite often.

> That sounded like you have a package in the AUR too.

No I was talking about the [README](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/README.md) file in this repo which point's to seppia's version since that one is considered "official".

**Comment by jstkdng** [comment]
@Ph0rk0z 
yes, I'm the maintainer of the ungoogled-chromium-git package, does chaotic-aur build that package?

**Comment by Ph0rk0z** [comment]
It started to recently. At 129-2 it wasn't' available.

**Comment by jstkdng** [comment]
@Ph0rk0z 
huh, oh well, if they build it then there is no point in my maintaining an obs repo. Will delete it later.

@wchen342 
eglGetMscRateCHROMIUM.patch is also a vaapi patch, chromium-drirc-disable-10bpc-color-configs.conf is also required though. hmmm
Regarding the ungoogled-chromium repo, it is "official" since it is the only one with that name. It would really be official until someone who is a part of the org also maintains it. I'm maintaining all the ungoogled-* packages, and, well, the rest is up to you.

**Comment by Ph0rk0z** [comment]
check, it doesn't tell me the source of the of the AUR it builds in pamac

**Comment by wchen342** [comment]
@jstkdng Well I don't know what happened before which leads to the current situation but since things have changed quite a bit I think we need to change how we connect from here to AUR too. I am not sure which way is better though, either let @Eloston adds you here or I add myself to one of the AUR package.

**Comment by jstkdng** [comment]
Adding me would be easier imo. And to connect to the aur I can set up an ssh key and add it as deployment key here.

**Comment by jstkdng** [comment]
@Ph0rk0z 
Can't we safely suppose that it is using the aur sources? Until we can guess I won't delete the obs pkg.

**Comment by Ph0rk0z** [comment]
yea, it's got to be yours: https://aur.archlinux.org/packages/?O=0&SeB=nd&K=ungoogled&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by jstkdng** [comment]
Doesn't the repo has build logs? that way we can know if it is truly using my sources.

**Comment by Ph0rk0z** [comment]
it might: https://lonewolf.pedrohlc.com/chaotic-aur/

**Comment by Eloston** [comment]
> I think we should add @jstkdng's -git repo too since he is now maintaining part of this repo and updates much more frequently.

As long as it's built from the code in this repo, I don't mind. Otherwise it'll become messy to maintain.

@jstkdng I've added you to the archlinux team which should let you share secrets securely. I don't think adding too many admins is necessarily a great idea (can make collaboration messy), but I'll leave the final decision to @wchen342 and @braewoods.

**Comment by wchen342** [comment]
@Eloston I think permissions can be fine-controlled? I am not too farmiliar with that but I think there is a section in the settings of each repository that control permissions.

**Comment by Eloston** [comment]
@wchen342 Permissions are defined by the access level. Each user and team has an associated access level. You need Admin level to set repository secrets (which is the highest permission level).

However, permission granularity isn't the main issue here. I'm just not convinced that adding more users with direct access to repo settings is a good idea for the same reasons that concurrent access to a shared resource is not an easy problem. Also, team discussions prevent any configuration conficts from breaking CI after the fact (at the cost of slower changes).

On the other hand, it may not be an issue right now; I'll let you guys decide what workflow is best.

**Comment by wchen342** [comment]
@Eloston I think a better way is you take some time to set up guidelines for managing each secondary-level repositories. Since the project keep growing and now each sub repo has different people as admins, this will cause inconsistency between repos and how secrets, issues, PRs and other stuffs are handled. Relying on several people discussing problems case by case may not be a good solution in long run.

**Comment by toluschr** [comment]
Im sorry, I was rebasing commits and made a mistake

**Comment by jstkdng** [comment]
uhh, ok I guess.
should we close this? as the original topic should be solved with the recent patches.
